openapi: 3.0.0
info:
  title: Renovation Man API
  description: Renovation Man form API
  version: 0.0.0
paths:
  /question:
    get:
      tags:
        - Question
      operationId: getQuestions
      summary: Returns all the Questions
      responses:
        '200':
          description: Return JSON Array of questions
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  $ref: "#/components/schemas/Question"
#  /question/{questionId}/reponse:
#    get:
#      tags:
#        - Question
#      operationId: getQuestionResponses
#      summary: Returns all the Responses for a Question
#      parameters:
#        - in: path
#          name: questionId
#          schema:
#            type: number
#          required: true
#      responses:
#        '200':
#          description: Return JSON Array of Responses
#          content:
#            application/json:
#              schema:
#                type: array
#                items:
#                  type:
#                  $ref: "#/components/schemas/Reponse"
components:
  schemas:
    Question:
      type: object
      properties:
        id:
          type: integer
          format: int64
        intitule:
          type: string
        reponses:
            type: array
            items:
              $ref: "#/components/schemas/Reponse"
    Reponse:
      type: object
      properties:
        id:
          type: integer
          format: int64
        intitule:
          type: string