spring:
  datasource:
    url: jdbc:mysql://${PROJET_RENOVATION_MAN_SERVER}:3306/${PROJET_RENOVATION_MAN_DATABASE}
    username: ${`PROJET_RENOVATION_MAN_USERNAME`}
    password: ${PROJET_RENOVATION_MAN_PASSWORD}